---
title: C. Differential Expression
author: Martin Morgan (mtmorgan@fredhutch.org)
output:
  BiocStyle::html_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{C. Differential Expression}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r style, echo=FALSE, results='asis'}
BiocStyle::markdown()
```

# Overview

## Research questions

## Overall work flow

Experimental design

Statistical approaches

# Experimental and statistical issues in depth

## Experimental design

Samples

- Unique identifier
- Factor(s) describing assignment of sample to treatment group(s)
- Covariates

Features

- Unique identifier. Sequence-based assays: often _genomic ranges_
- Additional annotations relevant to comprehension

Measurement

- Typically: _univariate_ measures
- Unique statistical properties from techincal aspects of experiment
- Shared experimental design across features

Principles

- Replication
- Simplicity
- Covariates
- Technical artifacts
- Batch effects

## Batch effects

Known

- Phenotypic covariates, e.g., age, gender
- Experimental covariates, e.g., lab or date of processing
- Incorporate into linear model, at least approximately

Unknown

- Or just unexpected / undetected
- Characterize using, e.g., `r Biocpkg("sva")`.

## Counting

## Normalization

TMM (`r Biocpkg("edgeR")`)

## Filtering

## Estimation

# Analysis of designed experiments in R

## Example: t-test

`t.test()`

- `x`: vector of univariate measurements
- `y`: `factor` describing experimental design
- `var.equal=TRUE`: appropriate for relatively small experiments where
  no additional information available?
- `formula`: alternative representation, `y ~ x`.

`lm()` and `anova()`

- `lm()`: fit _linear model_.
- `formula`: translated into _model matrix_, used in `lm.fit()`.
- `anova()`: statisitcal evaluation.

`genefilter::rowttests()`

- t-tests for gene expression data
- useful for exploratory analysis, but statistically sub-optimal
- `x`: matrix of expression values
- features x samples (reverse of how a 'statistician' would
  represent the data -- samples x features)

- `fac`: factor of one or two levels describing experimental design

Limitations

- Assumes features are _independent_
- Ignores common experimental design
- Ignores multiple testing

Consequences

- Poor estimate of between-group variance for each feature
- Elevated false discovery rate

## Common experimental designs

- t-test
- paired designs
- Single factor, multiple levels (one-way ANOVA) -- statistical
  contrasts
- Factorial designs -- main effects; interactions
- Simple time series

# Practical 

## Fast path: From BAM to differentially expressed genes

## Data exploration

## Quality metrics

## Down-stream: preview

# Transcript, single-cell, and other approaches to gene expression
